language: java
dist: trusty
jdk: oraclejdk8
install:
    - sudo apt-get install build-essential
    - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

script:
    - mvn compile
    - mvn evosuite:help
    - mvn evosuite:generate
    - mvn test
