language: java
dist: trusty
jdk: oraclejdk8
env:
  global:
    - CC_TEST_REPORTER_ID=7b6cabc60d29dbba80198d41999e8b08c3f9bd2b509c116631ab79b82fe46657
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

after_script:
  - ./cc-test-reporter after-build -t lcov --debug --exit-code $TRAVIS_TEST_RESULT
after_success:
  - bash <(curl -s https://codecov.io.bash)
install:
    - sudo apt-get install build-essential
    - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

script:
    - coverage run -m unittest discover
    - mvn compile
    - mvn evosuite:help
    - mvn evosuite:generate
    - mvn test
    - mvn cobertura:cobertura
